Feature: Inputs 컴포넌트
GDG-KU/GDG-KUDS-React pull request #11
Opened 2024-11-28 10:26 UTC by rla-suedeng

2024-11-28 23:57 UTC, mobius29 requested changes

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +      {/*class=gdg-kuds-input-primary gdg-kuds-input-small으로 붙는데 의도된 것인가 */}
의도 맞습니다!

후에 사용자 측에서 특정 부분에 대한 스타일을 변경하고 싶을 때 클래스명으로 접근할 수 있도록 하기 위함입니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  fontSize: '12px',
px단위는 number로도 가능합니다!

```typescript
{
  fontSize: 12,
}
```

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  display: 'flex',
`input` 태그는 기본적으로 **inline** 속성을 띄기 때문에 `inline-flex`로 들어가면 좋겠습니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  position: 'relative',
`relative` 속성은 `input` 상위의 `div` 태그에 들어가야 할 것 같습니다.

`position: absolute;` 속성은 부모 요소를 따라가면서 `position: static`이 아닌 요소들을 찾는데, 현재 아이콘과 `input`은 같은 레벨에 위치해서 제대로 동작이 되지 않을 수도 있습니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  transform: 'translateY(-50%)',
👍

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +      )}>
**label**과 **helpText**에 대한 class는 이 태그에서 정의되지 않아도 될 듯 합니다!

**label**에 대한 class는 `label` 태그에서, **helpText** 클래스는 아래 `p` 태그에서 사용하면 좋을 것 같습니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +          type={inputType === 'password' ? 'password' : 'primary'}
`input` 태그의 **type** 속성에는 **primary**라는 값이 존재하지 않습니다!

**inputProps** 안에 **type** 값이 있을거라 이 줄은 지워도 될 듯 합니다.

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +    ...inputProps
얘네는 기본값이 필요하지는 않을 것 같아요!

값이 없을 경우의 스타일은 DefaultStyle에 넣어두고, 값이 있는 경우만 생각해도 좋을 것 같습니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +    ...inputProps
그리고 **placeholder**, **disabled**같이 태그의 기본 속성이면서 컴포넌트 내부 로직에 영향을 주지 않는 애들은 지워주셔도 될 듯 합니다!

어차피 **inputProps** 안에 들어가기 때문에 작동엔 무리가 없을거고, 후에 필요할 때 꺼내써도 될 것 같습니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +type InputType = 'primary' | 'password';
**primary**와 **password**는 다른 의미를 가지고 있습니다!
**primary**는 디자인 시스템의 대표색상을, **password**는 `input` 태그가 가지는 타입을 의미하기 때문에 구분 부탁드립니다.

**primary**를 나타내기 위해서는 **colorType** 등의 이름으로 명시 부탁드립니다!

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  customSize?: Size;
**customSize**라는 명칭보단 **size**로 가져가도 좋을 듯 합니다.

2024-11-28 23:57 UTC, mobius29 commented on src/components/Input/Input.tsx
> +  helpText?: string;
**label**과 **helpText**는 `React.ReactNode` 타입으로 가져가도 좋을 듯 합니다!

2024-11-29 01:40 UTC, rla-suedeng commented on src/components/Input/Input.tsx
> +  customSize?: Size;
답변 감사합니다!
**size**로 갔을때 기존 InputHTMLAtributes에 있는 size와 충돌이 났어서 customSize로 수정을 하였는데 이부분 다시 시도해보겠습니다!

2024-11-29 04:12 UTC, BaconTomatoDeluxe submitted a review, later dismissed

2024-11-29 17:25 UTC, rla-suedeng commented
TextArea 별도 스토리북으로 구현했습니다!

2024-12-01 03:47 UTC, mobius29 approved these changes

2024-12-01 05:50 UTC, rla-suedeng commented on src/components/Input/Input.tsx
> +type InputType = 'text' | 'password'; //input 태그에 존재하나, 현재 text, password 외에는 추가된 것이 없어 그대로 가져가기로
그대로 가져가는 것도 좋은데 stories에서 보여질 때 text, password를 option으로 주냐, type을 string으로 치냐의 차이라서... 아니면 안내?를 위해서 stories에 password를 추가해도 될 거 같네요

2024-12-01 06:04 UTC, rla-suedeng commented
최종 수정 진행했습니다!

2024-12-02 00:54 UTC, mobius29 approved these changes

2024-12-02 00:56 UTC, merged