Feat/components/typography
GDG-KU/GDG-KUDS-React pull request #3
Opened 2024-11-18 05:42 UTC by BaconTomatoDeluxe

2024-11-18 13:36 UTC, mobius29 requested changes

2024-11-20 16:11 UTC, BaconTomatoDeluxe commented
prettier를 제외하고는 모두 반영했습니다.

2024-11-22 13:04 UTC, mobius29 submitted a review, later dismissed

2024-11-22 13:08 UTC, rla-suedeng submitted a review, later dismissed

2024-11-23 04:26 UTC, mobius29 approved these changes

2024-11-23 04:26 UTC, merged